sudo: required
language: generic
services:
    - docker
before_install:
    - docker build -t haris1822/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true haris1822/docker-react npm run test
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-211219075453"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY