sudo: required
language: generic
services:
    - docker
before_install:
    - docker build -t haris1822/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true haris1822/docker-react npm run test